name: uilibrary, release
on:
  release:
    types:
      - "published"

jobs:
  publish-pkg:
    name: uilibrary
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.0
          registry-url: https://npm.pkg.github.com
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}